//! Dovecot configuration management.
//!
//! Manages the Dovecot passwd-file user database and Sieve script paths.
//! Generates properly formatted entries for Dovecot's userdb/passdb.

use crate::{ConfigError, Domain, Result};

/// Default path for the Dovecot passwd-file.
pub const PASSWD_FILE_PATH: &str = "/etc/dovecot/users";

/// Default path for the platform-wide categories Sieve script (run by
/// LMTP `before` per-user scripts). Matches what's deployed.
pub const CATEGORIES_SIEVE_PATH: &str = "/etc/dovecot/sieve/categories.sieve";

/// Generate `90-sieve.conf` — wires the per-user `personal` script and the
/// platform `categories` `before`-script, and enables the `sieve`/
/// `imap_sieve` plugins on lmtp/imap.
///
/// `categories_path` is where the typed [`crate::categories::CategoryRules`]
/// gets compiled to a `.sieve` file at deploy time.
///
/// `enable_editheader` opts into the `editheader` extension so the audit
/// `X-PlausiDen-Category` header tagging works. Pigeonhole leaves it off
/// by default because it modifies messages — safe here because LMTP
/// delivery happens after DKIM signing for outbound and on inbound the
/// message is rewritten before storage anyway.
///
/// SECURITY: The `before`-script runs at LMTP delivery, before the user's
/// own Sieve, so a compromised user account cannot disable platform-wide
/// classification of their own mail. The user can still add rules that
/// override the categorization downstream — that's intentional.
#[must_use]
pub fn generate_sieve_runtime_conf(categories_path: &str, enable_editheader: bool) -> String {
    let editheader_line = if enable_editheader {
        "sieve_extensions = +editheader\n\n"
    } else {
        ""
    };
    format!(
        "# AUTO-GENERATED by mail-config::dovecot. Do not hand-edit.\n\
         # Dovecot 2.4 syntax: sieve_script <name> {{ ... }}; protocols enable via mail_plugins.\n\
         {editheader_line}\
         sieve_script personal {{\n\
         \x20\x20driver = file\n\
         \x20\x20path = ~/sieve\n\
         \x20\x20active_path = ~/.dovecot.sieve\n\
         }}\n\
         \n\
         sieve_script categories {{\n\
         \x20\x20type = before\n\
         \x20\x20driver = file\n\
         \x20\x20path = {categories_path}\n\
         }}\n\
         \n\
         protocol lmtp {{\n\
         \x20\x20mail_plugins {{\n\
         \x20\x20\x20\x20sieve = yes\n\
         \x20\x20}}\n\
         }}\n\
         \n\
         protocol imap {{\n\
         \x20\x20mail_plugins {{\n\
         \x20\x20\x20\x20imap_sieve = yes\n\
         \x20\x20}}\n\
         }}\n"
    )
}

/// Generate a Dovecot passwd-file entry for a mailbox.
///
/// Format: `user@domain:{scheme}password:vmail_uid:vmail_gid::/var/mail/vhosts/domain/user`
///
/// The password should already be hashed (SHA512-CRYPT recommended).
pub fn generate_passwd_entry(
    address: &str,
    password_hash: &str,
    vmail_uid: u32,
    vmail_gid: u32,
    mail_base: &str,
    domain: &str,
    local_part: &str,
) -> Result<String> {
    if address.is_empty() || !address.contains('@') {
        return Err(ConfigError::ValidationError {
            field: "address".into(),
            reason: "must be a valid email address".into(),
        });
    }
    Ok(format!(
        "{}:{}:{}:{}::{}/{}/{}/",
        address, password_hash, vmail_uid, vmail_gid, mail_base, domain, local_part
    ))
}

/// Parse existing Dovecot passwd-file entries.
/// Returns a list of (address, hash, uid, gid, home_path) tuples.
pub fn parse_passwd_file(content: &str) -> Vec<(String, String, String)> {
    content
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .filter_map(|line| {
            let parts: Vec<&str> = line.splitn(6, ':').collect();
            if parts.len() >= 2 {
                Some((
                    parts[0].to_string(),
                    parts[1].to_string(),
                    parts.get(5).unwrap_or(&"").to_string(),
                ))
            } else {
                None
            }
        })
        .collect()
}

/// Validate that a domain has at least one mailbox defined.
pub fn validate_domain(domain: &Domain) -> Result<()> {
    if domain.mailboxes.is_empty() {
        return Err(ConfigError::ValidationError {
            field: "mailboxes".into(),
            reason: format!("domain {} has no mailboxes", domain.name),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_valid_passwd_entry() {
        let entry = generate_passwd_entry(
            "tim@sacred.vote",
            "{SHA512-CRYPT}$6$abc$xyz",
            5000,
            5000,
            "/var/mail/vhosts",
            "sacred.vote",
            "tim",
        )
        .unwrap();
        assert!(entry.starts_with("tim@sacred.vote:"));
        assert!(entry.contains("/var/mail/vhosts/sacred.vote/tim/"));
    }

    #[test]
    fn reject_invalid_address() {
        assert!(
            generate_passwd_entry("noatsign", "hash", 5000, 5000, "/var/mail", "d", "u").is_err()
        );
        assert!(generate_passwd_entry("", "hash", 5000, 5000, "/var/mail", "d", "u").is_err());
    }

    #[test]
    fn sieve_runtime_conf_has_required_blocks() {
        let conf = generate_sieve_runtime_conf("/etc/dovecot/sieve/categories.sieve", false);
        assert!(conf.contains("sieve_script personal {"));
        assert!(conf.contains("sieve_script categories {"));
        assert!(conf.contains("type = before"));
        assert!(conf.contains("path = /etc/dovecot/sieve/categories.sieve"));
        assert!(conf.contains("protocol lmtp {"));
        assert!(conf.contains("protocol imap {"));
        assert!(conf.contains("sieve = yes"));
        assert!(conf.contains("imap_sieve = yes"));
        assert!(!conf.contains("editheader"));
    }

    #[test]
    fn sieve_runtime_conf_enables_editheader_on_request() {
        let conf = generate_sieve_runtime_conf("/etc/dovecot/sieve/categories.sieve", true);
        assert!(conf.contains("sieve_extensions = +editheader"));
    }

    #[test]
    fn parse_passwd_entries() {
        let content = "tim@sacred.vote:{SHA512-CRYPT}hash:5000:5000::/var/mail/vhosts/sacred.vote/tim/\n\
                        admin@sacred.vote:{SHA512-CRYPT}hash2:5000:5000::/var/mail/vhosts/sacred.vote/admin/\n";
        let entries = parse_passwd_file(content);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].0, "tim@sacred.vote");
    }
}
