//! Multi-tenant isolation: keeping one domain's mail out of another's.
//!
//! A single-tenant mail server and a multi-tenant one are not the same
//! system with a different number in it. Two settings that are correct and
//! ordinary when you host only your own domain become defects the moment
//! somebody else's mail arrives, and neither announces itself:
//!
//! 1. **`always_bcc`** is global. It copies EVERY message through the
//!    server to one mailbox. On a single-tenant host that is an archive of
//!    your own mail; add a second domain and it is a copy of someone
//!    else's correspondence, taken without telling them.
//!
//! 2. **An empty `smtpd_sender_login_maps`** means an authenticated
//!    session may use ANY envelope sender. On a single-tenant host every
//!    login is yours, so it reads as convenience; add a second domain and
//!    that tenant can send as you, and you as them.
//!
//! Both were live on plausiden-prime on 2026-09-11, found by auditing
//! AFTER the second domain was added rather than before. This module
//! exists so the generated config is right the first time for the third.
//!
//! Nothing here writes to disk. Every function returns the text of a map,
//! so a caller can diff it against what is deployed before touching a
//! running mail server.

use crate::domain::Domain;

/// Which domain's mail may be archived, and where.
///
/// The archive mailbox is normally on the operator's own domain, so it is
/// named separately from the domains being archived — archiving a tenant
/// into their own mailbox and archiving them into yours are very different
/// acts and should not be one field.
#[derive(Debug, Clone)]
pub struct ArchivePolicy {
    /// Domains whose mail is copied. ONLY list domains you own.
    pub archived_domains: Vec<String>,
    /// Where the copies go, e.g. `archive@plausiden.com`.
    pub archive_mailbox: String,
}

impl ArchivePolicy {
    /// Build the `recipient_bcc_maps` / `sender_bcc_maps` body.
    ///
    /// The same text serves both: a `@domain` key matches any address at
    /// that domain in either direction.
    ///
    /// Postfix applies a domain-wide fallback at lookup time that
    /// `postmap -q` does NOT apply, so `postmap -q user@example.com` on
    /// this map answers "no match" while delivery archives it correctly.
    /// Verify this by delivering a message, never by querying the map.
    #[must_use]
    pub fn to_bcc_map(&self) -> String {
        let mut out = String::from(
            "# Generated by mail-config::tenant — do not hand-edit.\n\
             #\n\
             # Deliberately NOT `always_bcc`, which is global and would copy\n\
             # every hosted domain's mail into this mailbox, including domains\n\
             # belonging to other people.\n\
             #\n\
             # Wire up as BOTH:\n\
             #   recipient_bcc_maps = hash:/etc/postfix/recipient_bcc\n\
             #   sender_bcc_maps    = hash:/etc/postfix/sender_bcc\n\
             # and ensure `always_bcc` is unset.\n\n",
        );
        for d in &self.archived_domains {
            out.push_str(&format!("@{}\t{}\n", d, self.archive_mailbox));
        }
        out
    }

    /// True when a domain's mail would be copied to the archive.
    #[must_use]
    pub fn archives(&self, domain: &str) -> bool {
        self.archived_domains.iter().any(|d| d == domain)
    }
}

/// An operator login and the domains it administers.
#[derive(Debug, Clone)]
pub struct Superuser {
    /// The login, e.g. `william@plausiden.com`.
    pub login: String,
    /// Domains it may send as any address on. NOT every hosted domain —
    /// a tenant's domain must be absent unless they have agreed to it.
    pub domains: Vec<String>,
}

impl Superuser {
    /// True when this operator administers `domain`.
    #[must_use]
    pub fn administers(&self, domain: &str) -> bool {
        self.domains.iter().any(|d| d == domain)
    }
}

/// Who may use which envelope sender on an authenticated session.
#[derive(Debug, Clone)]
pub struct SenderPolicy {
    /// An operator login permitted to send as any address on the domains
    /// it administers.
    ///
    /// Paul, 2026-09-11: "william should only be able to send as every
    /// plausiden email not literally every email." The scope is the point.
    /// An operator who can answer as `security@` or `noreply@` on their own
    /// domain is doing their job; one who can send as a client's address is
    /// a different thing, and hosting someone's mail should not quietly
    /// include the power to write as them.
    pub superuser: Option<Superuser>,
    /// Per-domain: the logins permitted to send as any address on it.
    ///
    /// Keyed by domain rather than by address so a tenant can send as
    /// `hello@`, `info@` and so on without an entry per alias — but never
    /// as another domain, which is the property that matters.
    pub domain_owners: Vec<(String, Vec<String>)>,
}

impl SenderPolicy {
    /// Every hosted domain, each owned by its own mailboxes.
    ///
    /// The safe default: a tenant may send as anything on their domain and
    /// nothing on anyone else's.
    #[must_use]
    pub fn self_owned(domains: &[Domain]) -> Self {
        Self {
            domain_owners: domains
                .iter()
                .map(|d| {
                    let logins = d
                        .mailboxes
                        .iter()
                        .map(|m| m.address(&d.name))
                        .collect::<Vec<_>>();
                    (d.name.clone(), logins)
                })
                .collect(),
            superuser: None,
        }
    }

    /// Name the operator login and the domains it administers.
    #[must_use]
    pub fn with_superuser(mut self, login: impl Into<String>, domains: &[String]) -> Self {
        self.superuser = Some(Superuser {
            login: login.into(),
            domains: domains.to_vec(),
        });
        self
    }

    /// Build the `smtpd_sender_login_maps` body.
    #[must_use]
    pub fn to_login_map(&self) -> String {
        let mut out = String::from(
            "# Generated by mail-config::tenant — do not hand-edit.\n\
             #\n\
             # address -> the login(s) permitted to use it as an envelope sender.\n\
             #\n\
             # Enforce on the SUBMISSION services only, in master.cf:\n\
             #   -o smtpd_sender_restrictions=reject_authenticated_sender_login_mismatch,permit_sasl_authenticated,reject\n\
             #\n\
             # NOT the bare `reject_sender_login_mismatch`, and NOT on port 25:\n\
             # that variant also rejects UNauthenticated senders, which would\n\
             # refuse ordinary inbound mail addressed to your own domains.\n\n",
        );
        if let Some(su) = &self.superuser {
            out.push_str(&format!(
                "# operator: {} — may send as any address on {}.\n\
                 # It is NOT added to any other domain's keys; hosting a domain\n\
                 # does not include the power to write as its owner.\n\n",
                su.login,
                su.domains.join(", ")
            ));
        }
        for (domain, logins) in &self.domain_owners {
            let op = self
                .superuser
                .as_ref()
                .filter(|su| su.administers(domain))
                .map(|su| su.login.clone());

            // Per-ADDRESS keys, not one key per domain: each mailbox gets
            // itself, plus the operator only where it administers. So team@
            // can still send as team@ without also sending as security@.
            for owner in logins {
                let mut allowed = vec![owner.clone()];
                if let Some(o) = &op {
                    if o != owner {
                        allowed.push(o.clone());
                    }
                }
                out.push_str(&format!("{}\t{}\n", owner, allowed.join(", ")));
            }
            // Fallback for addresses with no mailbox of their own: aliases,
            // and anything added later.
            match (&op, logins.is_empty()) {
                // Operator alone, so an alias added later cannot be spoofed
                // by an unrelated mailbox before anyone notices it exists.
                (Some(o), _) => out.push_str(&format!("@{domain}\t{o}\n")),
                // A tenant domain with no operator: no fallback key at all.
                // An empty value would match every address on the domain and
                // permit nobody, which reads as "configured" and is not.
                (None, false) => out.push_str(&format!(
                    "# @{domain} — no operator; only the addresses above may be sent as\n"
                )),
                (None, true) => out.push_str(&format!(
                    "# @{domain} — no mailboxes, so no login may send as it\n"
                )),
            }
            out.push('\n');
        }
        out
    }

    /// The logins permitted to send as `domain`, if any.
    #[must_use]
    pub fn owners_of(&self, domain: &str) -> Option<&[String]> {
        self.domain_owners
            .iter()
            .find(|(d, _)| d == domain)
            .map(|(_, l)| l.as_slice())
    }

    /// True when `login` may send as an address on `domain`.
    #[must_use]
    pub fn may_send_as(&self, login: &str, domain: &str) -> bool {
        // The operator may send as any address on the domains it
        // ADMINISTERS. Not every hosted domain, and not the whole
        // internet: an unadministered or unhosted domain falls through to
        // the ordinary per-address check below.
        if let Some(su) = &self.superuser {
            if su.login == login && su.administers(domain) && self.owners_of(domain).is_some() {
                return true;
            }
        }
        self.owners_of(domain)
            .is_some_and(|l| l.iter().any(|o| o == login))
    }
}

/// Reconstruct the hosted domains from a deployed Postfix `vmailbox` map.
///
/// A tool that can only emit config for a server it also built is no use on
/// a server that already exists — which is every server worth securing.
/// This reads the mailbox map that is actually deployed and derives the
/// tenant structure from it, so the emitted maps can be diffed against
/// reality rather than against an aspiration.
///
/// Lines are `address<whitespace>path`. Anything without an `@`, and
/// anything commented or blank, is skipped rather than guessed at.
#[must_use]
pub fn domains_from_vmailbox(lines: &[String]) -> Vec<Domain> {
    use std::collections::BTreeMap;
    let mut by_domain: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for line in lines {
        let Some(addr) = line.split_whitespace().next() else {
            continue;
        };
        let Some((local, domain)) = addr.rsplit_once('@') else {
            continue;
        };
        if local.is_empty() || domain.is_empty() {
            continue;
        }
        let locals = by_domain.entry(domain.to_ascii_lowercase()).or_default();
        let local = local.to_ascii_lowercase();
        if !locals.contains(&local) {
            locals.push(local);
        }
    }
    by_domain
        .into_iter()
        .map(|(name, locals)| Domain {
            name,
            dkim_enabled: true,
            dkim_selector: "default".to_owned(),
            mailboxes: locals
                .into_iter()
                .map(|local_part| crate::domain::Mailbox {
                    local_part,
                    kind: crate::domain::MailboxKind::User,
                    display_name: None,
                })
                .collect(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{Mailbox, MailboxKind};

    fn dom(name: &str, locals: &[&str]) -> Domain {
        Domain {
            name: name.to_owned(),
            dkim_enabled: true,
            dkim_selector: "default".to_owned(),
            mailboxes: locals
                .iter()
                .map(|l| Mailbox {
                    local_part: (*l).to_owned(),
                    kind: MailboxKind::User,
                    display_name: None,
                })
                .collect(),
        }
    }

    fn ours_and_theirs() -> Vec<Domain> {
        vec![
            dom("plausiden.com", &["william", "team"]),
            dom("breeziside.com", &["golf", "dmarc"]),
        ]
    }

    #[test]
    fn a_tenant_cannot_send_as_our_domain() {
        let p = SenderPolicy::self_owned(&ours_and_theirs());
        assert!(!p.may_send_as("golf@breeziside.com", "plausiden.com"));
        assert!(!p.may_send_as("dmarc@breeziside.com", "plausiden.com"));
    }

    #[test]
    fn without_a_superuser_nobody_crosses_a_domain_boundary_in_either_direction() {
        // The default is symmetric. It would be easy to write this rule as
        // "protect ours from theirs" and leave the operator silently able
        // to send as a client, which is worse because nobody would notice.
        let p = SenderPolicy::self_owned(&ours_and_theirs());
        assert!(!p.may_send_as("william@plausiden.com", "breeziside.com"));
        assert!(!p.may_send_as("golf@breeziside.com", "plausiden.com"));
    }

    #[test]
    fn the_operator_may_send_as_any_address_on_a_domain_it_administers() {
        let p = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()]);
        assert!(p.may_send_as("william@plausiden.com", "plausiden.com"));
    }

    #[test]
    fn the_operator_may_not_send_as_a_tenant_it_merely_hosts() {
        // Paul, 2026-09-11, correcting the previous revision: "william
        // should only be able to send as every plausiden email not
        // literally every email." Hosting someone's domain must not
        // silently include the power to write as them.
        let p = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()]);
        assert!(!p.may_send_as("william@plausiden.com", "breeziside.com"));
        let m = p.to_login_map();
        assert!(
            !m.contains("golf@breeziside.com\tgolf@breeziside.com, william@plausiden.com"),
            "operator must not appear on a tenant's address:\n{m}"
        );
        assert!(
            !m.contains("@breeziside.com\twilliam@plausiden.com"),
            "operator must not hold the tenant's fallback key:\n{m}"
        );
    }

    #[test]
    fn a_tenant_domain_gets_no_fallback_key_at_all() {
        let p = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()]);
        let m = p.to_login_map();
        assert!(m.contains("# @breeziside.com — no operator"), "\n{m}");
        assert!(
            m.contains("golf@breeziside.com\tgolf@breeziside.com\n"),
            "\n{m}"
        );
    }

    #[test]
    fn an_operator_over_two_of_its_own_domains_covers_both() {
        let mut ds = ours_and_theirs();
        ds.push(dom("plausiden.org", &["hello"]));
        let p = SenderPolicy::self_owned(&ds).with_superuser(
            "william@plausiden.com",
            &["plausiden.com".to_owned(), "plausiden.org".to_owned()],
        );
        assert!(p.may_send_as("william@plausiden.com", "plausiden.org"));
        assert!(!p.may_send_as("william@plausiden.com", "breeziside.com"));
    }

    #[test]
    fn only_the_superuser_gets_that_power() {
        let p = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()]);
        // team@ is on OUR domain and still cannot reach a tenant's.
        assert!(!p.may_send_as("team@plausiden.com", "breeziside.com"));
        // ...and still cannot send as another address on its own domain,
        // because keys are per-address now, not per-domain.
        assert!(!p.may_send_as("golf@breeziside.com", "plausiden.com"));
    }

    #[test]
    fn the_superuser_is_not_a_wildcard_over_the_whole_internet() {
        // A domain we do not host has no map entry at all, so the mismatch
        // check refuses it for everyone. Worth pinning: "send as anything"
        // is easy to read as "send as gmail.com".
        let p = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()]);
        assert!(!p.may_send_as("william@plausiden.com", "gmail.com"));
        assert!(!p.may_send_as("william@plausiden.com", "irs.gov"));
    }

    #[test]
    fn the_map_gives_each_address_itself_plus_the_superuser() {
        let m = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()])
            .to_login_map();
        assert!(m.contains("team@plausiden.com\tteam@plausiden.com, william@plausiden.com"));
        // NOT the tenant's address — see the_operator_may_not_send_as_a_tenant.
        assert!(m.contains("golf@breeziside.com\tgolf@breeziside.com\n"));
        // The superuser is not listed twice against its own address.
        assert!(
            m.contains("william@plausiden.com\twilliam@plausiden.com\n"),
            "superuser's own key should not repeat it:\n{m}"
        );
    }

    #[test]
    fn an_unlisted_alias_falls_back_to_the_superuser_alone() {
        // security@ has no mailbox in this fixture. The @domain key must
        // not hand it to every mailbox on the domain.
        let m = SenderPolicy::self_owned(&ours_and_theirs())
            .with_superuser("william@plausiden.com", &["plausiden.com".to_owned()])
            .to_login_map();
        assert!(m.contains("@plausiden.com\twilliam@plausiden.com\n"));
    }

    #[test]
    fn each_login_may_send_as_its_own_domain() {
        let p = SenderPolicy::self_owned(&ours_and_theirs());
        assert!(p.may_send_as("golf@breeziside.com", "breeziside.com"));
        assert!(p.may_send_as("william@plausiden.com", "plausiden.com"));
        assert!(p.may_send_as("team@plausiden.com", "plausiden.com"));
    }

    #[test]
    fn the_login_map_gives_every_mailbox_its_own_key() {
        // This test used to assert a per-DOMAIN key listing every mailbox
        // on it. That was looser than it looked: it let team@ send as
        // security@ purely because both are on plausiden.com. Keys are now
        // per address, so each mailbox may send as itself and no more.
        let m = SenderPolicy::self_owned(&ours_and_theirs()).to_login_map();
        for a in [
            "william@plausiden.com",
            "team@plausiden.com",
            "golf@breeziside.com",
            "dmarc@breeziside.com",
        ] {
            assert!(
                m.contains(&format!("{a}\t{a}\n")),
                "{a} missing its own key:\n{m}"
            );
        }
        // And with no operator named, no domain-wide fallback exists at all.
        //
        // Checked line-anchored, not by substring: "team@plausiden.com\t..."
        // CONTAINS "@plausiden.com\t", so a contains() check here passes
        // for the wrong reason and would keep passing if a real fallback
        // key appeared.
        assert!(
            !m.lines().any(|l| l.starts_with("@plausiden.com\t")),
            "no domain-wide key should exist without an operator:\n{m}"
        );
        assert!(m.contains("# @plausiden.com — no operator"), "\n{m}");
        assert!(m.contains("# @breeziside.com — no operator"), "\n{m}");
    }

    #[test]
    fn a_domain_with_no_mailboxes_gets_no_key() {
        // An empty value would be a map entry matching everything, which is
        // the failure this whole module exists to prevent.
        let p = SenderPolicy::self_owned(&[dom("parked.example", &[])]);
        let m = p.to_login_map();
        assert!(
            !m.contains("@parked.example\t"),
            "must not emit an empty value:\n{m}"
        );
        assert!(
            m.contains("# @parked.example"),
            "should say why it is absent"
        );
        assert!(p
            .owners_of("parked.example")
            .is_some_and(<[String]>::is_empty));
        assert!(!p.may_send_as("anyone@anywhere", "parked.example"));
    }

    #[test]
    fn the_login_map_carries_the_submission_only_warning() {
        // The bare reject_sender_login_mismatch on port 25 refuses normal
        // inbound mail. Anyone deploying this map needs to read that before
        // they paste a restriction list, so it ships with the map.
        let m = SenderPolicy::self_owned(&ours_and_theirs()).to_login_map();
        assert!(m.contains("reject_authenticated_sender_login_mismatch"));
        assert!(m.contains("NOT on port 25"));
    }

    #[test]
    fn the_archive_covers_our_domain_and_not_a_tenants() {
        let p = ArchivePolicy {
            archived_domains: vec!["plausiden.com".to_owned()],
            archive_mailbox: "archive@plausiden.com".to_owned(),
        };
        assert!(p.archives("plausiden.com"));
        assert!(!p.archives("breeziside.com"));
        let m = p.to_bcc_map();
        assert!(m.contains("@plausiden.com\tarchive@plausiden.com"));
        assert!(!m.contains("breeziside"));
    }

    #[test]
    fn the_bcc_map_warns_that_postmap_q_lies_about_it() {
        // A deployer who checks the map with `postmap -q` sees "no match"
        // and concludes the fix failed. It cost an hour once.
        let m = ArchivePolicy {
            archived_domains: vec!["plausiden.com".to_owned()],
            archive_mailbox: "archive@plausiden.com".to_owned(),
        }
        .to_bcc_map();
        assert!(m.contains("always_bcc"), "should say what NOT to use");
    }

    #[test]
    fn domains_are_reconstructed_from_a_deployed_vmailbox() {
        let lines: Vec<String> = [
            "william@plausiden.com\tplausiden.com/william/",
            "team@plausiden.com    plausiden.com/team/",
            "golf@breeziside.com\tbreeziside.com/golf/",
            "dmarc@breeziside.com\tbreeziside.com/dmarc/",
        ]
        .iter()
        .map(|s| (*s).to_owned())
        .collect();
        let ds = domains_from_vmailbox(&lines);
        assert_eq!(ds.len(), 2, "one entry per domain");
        let p = SenderPolicy::self_owned(&ds);
        assert!(p.may_send_as("golf@breeziside.com", "breeziside.com"));
        assert!(!p.may_send_as("golf@breeziside.com", "plausiden.com"));
    }

    #[test]
    fn malformed_vmailbox_lines_are_skipped_not_guessed() {
        let lines: Vec<String> = [
            "",
            "# a comment",
            "no-at-sign-here    somewhere/",
            "@nolocal.example   x/",
            "trailing@   y/",
            "good@example.com   example.com/good/",
        ]
        .iter()
        .map(|s| (*s).to_owned())
        .collect();
        let ds = domains_from_vmailbox(&lines);
        assert_eq!(ds.len(), 1, "only the well-formed line counts, got {ds:?}");
        assert_eq!(ds[0].name, "example.com");
    }

    #[test]
    fn addresses_are_case_folded_so_one_domain_is_one_tenant() {
        // Postfix is case-insensitive here. Two spellings arriving as two
        // domains would emit two map keys, and the second would look like
        // an unowned domain anyone could send as.
        let lines: Vec<String> = ["a@Example.COM  x/", "B@example.com  y/"]
            .iter()
            .map(|s| (*s).to_owned())
            .collect();
        let ds = domains_from_vmailbox(&lines);
        assert_eq!(ds.len(), 1, "got {ds:?}");
        assert_eq!(ds[0].mailboxes.len(), 2);
    }

    #[test]
    fn an_archive_policy_naming_a_tenant_is_representable_but_obvious() {
        // Not forbidden — the operator may have consent. But it must be an
        // explicit list entry, never a side effect of a global setting.
        let p = ArchivePolicy {
            archived_domains: vec!["plausiden.com".to_owned(), "breeziside.com".to_owned()],
            archive_mailbox: "archive@plausiden.com".to_owned(),
        };
        assert!(p.archives("breeziside.com"));
        assert!(p
            .to_bcc_map()
            .contains("@breeziside.com\tarchive@plausiden.com"));
    }
}
